name: Test on pull request
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    # Run only on non-merged non-draft mergeable pull requests
    if: |
      !(
        (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
        && !github.event.pull_request.draft
        && !github.event.pull_request.merged
        && github.event.pull_request.merge_commit_sha != null
      )
    steps:
      - name: Check out merge commit of pull request
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Test
        run: |
          chmod +x ./test/test.sh
          ./test/test.sh
